version: "3"

services:
  app:
    build: .
    env_file: .env
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"

  database:
    image: mysql:5.7.17
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
